# Generated by Django 3.1.5 on 2021-04-17 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topsongs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('youtube_link', models.URLField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topsongs.band')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topsongs.genre')),
            ],
        ),
    ]
