# Generated by Django 3.1.5 on 2021-04-17 08:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topsongs', '0002_genre_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
