# Generated by Django 3.1.5 on 2021-04-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topsongs', '0003_auto_20210417_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='youtube_link',
            new_name='video',
        ),
    ]
