# Generated by Django 3.1.5 on 2021-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topsongs', '0004_auto_20210417_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.URLField(),
        ),
    ]
