# Generated by Django 3.1.5 on 2021-04-17 10:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topsongs', '0005_auto_20210417_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
