# Generated by Django 3.1.5 on 2021-04-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topsongs', '0011_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='playlist',
            new_name='playlists',
        ),
    ]
